### ISSUE TITLE
Now working in the 3.1.2 version of the Glyphs app

### ISSUE THREAD

**Issue by viterzbayraku** [mekkablue/Stitcher#1]
I was created the component, and called his name on the parameters popup. But after entering the name of the component, the outline of the symbol disappears altogether, and the component itself does not appear as a repeating element.

**Comment by mekkablue** [comment]
Cannot reproduce. Can you try again with the latest version of the plug-in and Glyphs 3.2?

**Comment by viterzbayraku** [comment]
Version 3.2 still unavailable for me. 3.1.2 marked as latest in updates )

**Comment by schriftgestalt** [comment]
To get a pre-release version of Glyphs 3.2, activate "Show Cutting edge versions" in Preferences > Update".

**Comment by viterzbayraku** [comment]
> 

It's working in the beta version of Glyphs. Thank you )
