### ISSUE TITLE
As custom parameter - Background option doesn't work

### ISSUE THREAD

**Issue by guillaumeruiz** [mekkablue/Stitcher#2]
Hello,
I tried to use Stitcher as a custom parameter (Prefilter) and it works but i still getting the original path in any case (checking to use background or not). It looks like the "background" option doesn't work with custom parameter.
Here is an exemple when i copy the parameter from Stitcher.
Did i miss something ? How can i do ?

Thank you for your help,
Guillaume

"{
	customParameters = (
		{
			name = Filter;
			value = "Stitcher; component:_circle; interval:70.0; balance:1";
		}
	);
}"

**Comment by mekkablue** [comment]
> "background" option doesn't work with custom parameter

It is not possible to access the background when processing as a custom parameter. The background is part of the master layers you edit. But custom parameters work on an interpolated layer.
